version: '3.3'
services:
  server:
    image: nginx:1.15
    container_name: moved_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site:/usr/share/nginx/html
      - ./nginx/my-site.com.crt:/etc/nginx/my-site.com.crt
      - ./nginx/my-site.com.key:/etc/nginx/my-site.com.key
    ports:
    - "9090:80"
    - "4404:443"
    networks:
      - apps_default

networks:
  apps_default:
    driver: bridge